#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="student")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void Insertstu(stu instance);
  partial void Updatestu(stu instance);
  partial void Deletestu(stu instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["studentConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<stu> stu
	{
		get
		{
			return this.GetTable<stu>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.StoredProcedure1")]
	public int StoredProcedure1([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string xh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), xh, name);
		return ((int)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.stu")]
public partial class stu : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _stu_xh;
	
	private string _stu_name;
	
	private string _stu_class;
	
	private System.Nullable<double> _st_cj;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onstu_xhChanging(string value);
    partial void Onstu_xhChanged();
    partial void Onstu_nameChanging(string value);
    partial void Onstu_nameChanged();
    partial void Onstu_classChanging(string value);
    partial void Onstu_classChanged();
    partial void Onst_cjChanging(System.Nullable<double> value);
    partial void Onst_cjChanged();
    #endregion
	
	public stu()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stu_xh", DbType="NVarChar(20)")]
	public string stu_xh
	{
		get
		{
			return this._stu_xh;
		}
		set
		{
			if ((this._stu_xh != value))
			{
				this.Onstu_xhChanging(value);
				this.SendPropertyChanging();
				this._stu_xh = value;
				this.SendPropertyChanged("stu_xh");
				this.Onstu_xhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stu_name", DbType="NVarChar(20)")]
	public string stu_name
	{
		get
		{
			return this._stu_name;
		}
		set
		{
			if ((this._stu_name != value))
			{
				this.Onstu_nameChanging(value);
				this.SendPropertyChanging();
				this._stu_name = value;
				this.SendPropertyChanged("stu_name");
				this.Onstu_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stu_class", DbType="NVarChar(20)")]
	public string stu_class
	{
		get
		{
			return this._stu_class;
		}
		set
		{
			if ((this._stu_class != value))
			{
				this.Onstu_classChanging(value);
				this.SendPropertyChanging();
				this._stu_class = value;
				this.SendPropertyChanged("stu_class");
				this.Onstu_classChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_cj", DbType="Float")]
	public System.Nullable<double> st_cj
	{
		get
		{
			return this._st_cj;
		}
		set
		{
			if ((this._st_cj != value))
			{
				this.Onst_cjChanging(value);
				this.SendPropertyChanging();
				this._st_cj = value;
				this.SendPropertyChanged("st_cj");
				this.Onst_cjChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
